accounts/urls.py
from django.urls import path

from .views import SignupView

app_name = "accounts"

urlpatterns = [
    path("signup/",SignupView.as_view(), name = "signup"),

]

blog/urls.py
from django.urls import path

from .views import PostListView,PostDetailView,AddPost
from .views import EditPost,DeletePost

app_name = "blog"

urlpatterns = [
    path("",PostListView.as_view(), name = "home"),
    path("<int:pk>/",PostDetailView.as_view(), name = "detail"),
    path("newpost/",AddPost.as_view(), name="newpost"),
    path("<int:pk>/edit/",EditPost.as_view(), name="editpost"),
    path("<int:pk>/delete/",DeletePost.as_view(), name="deletepost"),
    

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls")),
    path("accounts/",include("django.contrib.auth.urls")),
    path("accounts/",include("accounts.urls")),
    


]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse,reverse_lazy
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE)
    body = models.TextField()

    def __str__ (self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail",args=[str(self.id)])

accounts/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy,reverse

""" we can also use this from django.views.generic import CreateView """
from django.views import generic
# Create your views here.

class SignupView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("login")

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy,reverse

from .models import Post
# Create your views here.

class PostListView(ListView):
    model = Post
    template_name = "blog/home.html"

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/detail.html"

class AddPost(CreateView):
    model = Post
    template_name = "blog/newpost.html"
    fields = "__all__"

class EditPost(UpdateView):
    model = Post
    template_name = "blog/editpost.html"
    fields = ["title","body"]

class DeletePost(DeleteView):
    model = Post
    template_name = "blog/deletepost.html"
    success_url = reverse_lazy("blog:home")

accounts/templates/accounts/signup.html
{% extends 'blog/base.html' %}

{% block title %} Create new account {% endblock title %}

{% block content %}

<div class="signup-block">
  <h3>Create new account</h3>
  <form class="" action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" name="button">Sign Up</button>
  </form>
</div>

{% endblock content %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
  </head>
  <body>
    <header>
      <div class="site-urls">
        <a href="{% url 'blog:home' %}">Home</a>
      </div>
      <div class="login-urls">
        {% if user.is_authenticated %}
          <p>Hi {{user.username}}!</p> <a href="{% url 'logout' %}">Log out</a>
        {% else %}
          <p>You are not logged in</p>
          <a href="{% url 'login' %}">Log In</a>
        {% endif %}
      </div>
      <div class="newpost">
        <a href="{% url 'blog:newpost' %}">+newpost</a>
      </div>
    </header>

    {% block content %}

    {% endblock content %}

  </body>
</html>

blog/templates/blog/deletepost.html
{% extends 'blog/base.html' %}

{% block title %}Deleting {{object.title}} {% endblock title %}


{% block content %}

<div class="delete-post">
  <h4> Delete {{object.title}} Post</h4>
  <form class="" action="" method="post">
    {% csrf_token %}
    <button type="submit" name="button">Delete Post</button>
  </form>
</div>

{% endblock content %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}details of {{object.title}} {% endblock title %}

{% block content %}
<div class="post-detail">
  <h4>{{object.title}} by {{object.author}}</h4>
  <p>{{object.body}}</p>
  <a href="{% url 'blog:editpost' object.pk %}">Edit post</a> | <a href="{% url 'blog:deletepost' object.pk %}">Delete Post</a>
</div>

{% endblock content %}

blog/templates/blog/editpost.html
{% extends 'blog/base.html' %}

{% block title %}Editing {{object.text}} {% endblock title %}

{% block content %}

<div class="edit-post">
  <h3>Edit {{object.title}}</h3>
  <form class="" action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" name="button">Update Post</button>
  </form>
</div>

{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %} Home Page {%endblock title %}

{% block content %}

<div class="home-block">
  {% if object_list %}
    {% for post in  object_list %}
      <h5><a href="{% url 'blog:detail' post.pk %}">{{post.title}}</a></h5>
      <p>{{post.body}}</p>
    {% endfor %}
  {% else %}
    <p>No posts.</p> <a href="#">+New Post</a>
  {% endif %}
</div>

{% endblock content %}

blog/templates/blog/newpost.html
{% extends 'blog/base.html' %}

{% block title %} New Post {% endblock title %}

{% block content %}

<div class="new-post">
  <h2>Add newpost</h2>
  <form class=""  method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" name="button">Add Post</button>
  </form>
</div>

{% endblock content %}